services:
  traefik-dev:
    image: traefik:v2.11.0
    command:
      - --api.insecure=true
      - --api.dashboard=true
      - --providers.docker=true
      - --providers.docker.exposedbydefault=false
      - --entrypoints.web.address=:8888
    labels:
      - traefik.enable=true
      - traefik.http.routers.traefik.rule=Host(`traefik.localhost`)
      - traefik.http.routers.traefik.entrypoints=web
      - traefik.http.routers.traefik.service=api@internal
    ports:
      - 80:8888
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    restart: always

  leagueify-marketing-dev:
    image: nginx
    labels:
      - traefik.enable=true
      - traefik.http.routers.leagueify-marketing-dev.rule=Host(`localhost`)
      - traefik.http.routers.leagueify-marketing-dev.entrypoints=web
      - traefik.http.middlewares.leagueify-marketing-dev.ratelimit.average=100
    volumes:
      - ./marketing/:/usr/share/nginx/html

volumes:
  database:
